import fs from 'node:fs';
import path from 'node:path';
import {root} from './reference.mjs';

// Sources deliberately use named imports/exports only. The build joins their
// dependency order into one lexical scope; the browser needs no module loader.
export function bundle(files, publicNames) {
  const sources = files.map(name => {
    const source = fs.readFileSync(path.join(root, 'src', name), 'utf8');
    return `// ---- ${name} ----\n` + source.replace(/^import\s[\s\S]*?;\r?\n/gm, '').replace(/\bexport\s+(?=(?:const|let|function|class)\b)/g, '');
  });
  return `// Generated by scripts/build.mjs. Edit src/, then rebuild.\n(function () {\n'use strict';\n${sources.join('\n')}\nglobalThis.NadduCore = {${publicNames.join(',')}};\n})();\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.join(root, 'scripts/build.mjs')) {
  const output = path.join(root, 'build/minifish.js');
  fs.mkdirSync(path.dirname(output), {recursive: true});
  fs.writeFileSync(output, bundle(['constants.mjs', 'generated/magics.mjs', 'bitboard.mjs'],
    ['MAX_PLY','make_move','c_div','make_key','sq_bb','attacks_bb_rook','attacks_bb_bishop','BetweenBB']));
  console.log('Built build/minifish.js');
}
