import fs from 'node:fs';
import path from 'node:path';
import {root} from './reference.mjs';

// Sources deliberately use named imports/exports only. The build joins their
// dependency order into one lexical scope; the browser needs no module loader.
export function bundle(files, publicNames) {
  const sources = files.map(name => {
    const source = fs.readFileSync(path.join(root, 'src', name), 'utf8').replace(/\r\n/g,'\n');
    return `// ---- ${name} ----\n` + source.replace(/^import\s[\s\S]*?;\r?\n/gm, '').replace(/\bexport\s+(?=(?:const|let|function|class)\b)/g, '');
  });
  return `// Generated by scripts/build.mjs. Edit src/, then rebuild.\n(function () {\n'use strict';\n${sources.join('\n')}\nglobalThis.NadduCore = {${publicNames.join(',')}};\n})();\n`;
}

export const CORE_FILES = ['constants.mjs','generated/magics.mjs','bitboard.mjs',
  'generated/nnue.mjs','nnue.mjs','position.mjs','movegen.mjs','evaluate.mjs','notation.mjs',
  'tt.mjs','history.mjs','movepick.mjs','control.mjs','timeman.mjs','search.mjs'];
export const CORE_NAMES = ['MAX_PLY','make_move','c_div','make_key','sq_bb','attacks_bb_rook','attacks_bb_bishop','BetweenBB',
  'NNUE','nnue_evaluate','evaluate','Position','do_move','undo_move','generate_legal','StartFEN','set_position','uci_move',
  'TT','tt_probe','tt_allocate','Threads','Limits','EngineOptions','set_output','start_thinking'];
export function release_bundle() { return bundle([...CORE_FILES,'generated/benchmark.mjs','smp.mjs','uci.mjs','entry.mjs'],[...CORE_NAMES,'EngineUCI']); }

if (process.argv[1] && path.resolve(process.argv[1]) === path.join(root, 'scripts/build.mjs')) {
  const output = path.join(root, 'build/minifish.js');
  fs.mkdirSync(path.dirname(output), {recursive: true});
  fs.writeFileSync(output,bundle(CORE_FILES,CORE_NAMES));
  fs.writeFileSync(path.join(root,'naddu.js'),release_bundle());
  console.log('Built naddu.js and build/minifish.js');
}
