"""Export exact literal data; never translate integers through floating point."""
import argparse
import ast
import base64
import hashlib
import struct
from pathlib import Path
from reference import ROOT, REFERENCE, verify_reference


def literals(filename):
    tree = ast.parse((REFERENCE / filename).read_text(encoding="utf-8"))
    result = {}
    for node in tree.body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            try:
                result[node.targets[0].id] = ast.literal_eval(node.value)
            except (ValueError, TypeError):
                pass
    return result


def flatten(values):
    for v in values:
        if isinstance(v, (list, tuple)):
            yield from flatten(v)
        else:
            yield v


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("kind", choices=("magics", "nnue"))
    args = parser.parse_args()
    verify_reference()
    source = "bitboard.py" if args.kind == "magics" else "nnue_weights.py"
    values = literals(source)
    digest = hashlib.sha256((REFERENCE / source).read_bytes()).hexdigest()
    text = f"// Generated by scripts/export_data.py from {source}; SHA-256 {digest}.\n"
    if args.kind == "magics":
        for name in ("bishop", "rook"):
            text += "export const " + name.upper() + "_MAGICS = [\n"
            text += ",\n".join("  " + str(row[0]) + "n" for row in values[name + "_init"])
            text += "\n];\n"
    else:
        network = list(flatten(values["FEATURE_TRANSFORMER_WEIGHTS"]))
        network += values["FEATURE_TRANSFORMER_BIASES"] + values["OUTPUT_WEIGHTS"] + [values["OUTPUT_BIAS"]]
        assert len(network) == 49345
        assert all(-32768 <= v <= 32767 for v in network)
        packed = struct.pack("<" + "h" * len(network), *network)
        text += f"export const NETWORK_SHA256 = '{hashlib.sha256(packed).hexdigest()}';\n"
        text += "export const NETWORK_BASE64 =\n"
        encoded = base64.b64encode(packed).decode()
        text += " +\n".join("  '" + encoded[i:i+120] + "'" for i in range(0, len(encoded), 120)) + ";\n"
    destination = ROOT / "src/generated" / (args.kind + ".mjs")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(text, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
